### ISSUE TITLE
conflict with sdk version in flutter

### ISSUE THREAD

**Issue by jeffmiller16** [passsy/dart-lint#28]
flutter pub get
Running "flutter pub get" in appname...                       
The current Dart SDK version is 2.10.4.

Because appname depends on lint >=1.5.0 which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.
pub get failed (1; Because appname depends on lint >=1.5.0 which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.)
exit code 1

**Comment by passsy** [comment]
`lint: 1.5.0` is only compatible with Dart `2.12`. You're using an older Dart version, so you have to use an older `lint` version. `pub` picks the latest compatible version automatically for you. Always place `lint: ^1.0.0` in your `pubspec.yaml`.

```yaml
dev_dependencies:
  lint: ^1.0.0
```
