### ISSUE TITLE
Inspect 'Annotator' options

### ISSUE THREAD

**Issue by Tomic-Riedel** [passsy/dart-lint#34]
Hey!
I just set up lint on my project (Relatively late because I just found out about it now) and I get the error "Inspect 'Annotator' options" in a lot of places. What does this error mean and how can I fix it?

The error occurs both in widgets, as in variables, etc.

I would be very happy about an answer,

LG

**Comment by passsy** [comment]
Never heard of it, do you have a screenshot? It sounds more like an error from `IntelliJ` https://www.jetbrains.com/help/phpstorm/general-annotator.html. Which version are you using?

**Comment by alexander-doroshko** [comment]
It's an IntelliJ-related issue which has been fixed. The fix will be available in 2023.1 release (all JetBrains IDEs).We'll see if we can include this fix in earlier IDE bugfix updates.
Please close this issue, I don't have permissions here.
