### ISSUE TITLE
How to turn off "The argument type 'dynamic' can't be assigned to the parameter type x"?

### ISSUE THREAD

**Issue by Hassanmsaid** [passsy/dart-lint#37]
I want to disable the lint: "The argument type 'dynamic' can't be assigned to the parameter type x" but I can't find it.

**Update**
I used this and the problem is **solved**!
```
analyzer:
  strong-mode:
    implicit-casts: true
```

**Comment by passsy** [comment]
Definitly not recommending it, because this will lead to errors at runtime.
See https://github.com/passsy/dart-lint/issues/15#issuecomment-771734437

**Comment by Hassanmsaid** [comment]
> Definitly not recommending it, because this will lead to errors at runtime.
> See [#15 (comment)](https://github.com/passsy/dart-lint/issues/15#issuecomment-771734437)

Thank you passsy, I understand you but I am using implicit cast hundreds of times in my project so I cannot check it right now.
