### ISSUE TITLE
Exclude {Key? key} from 'Put required named parameters first' rule

### ISSUE THREAD

**Issue by esenmx** [passsy/dart-lint#39]
Since Flutter source code full of `{Key? key, required ...}` constructors, it would be better excluding this specific case.

<img width="569" alt="Screen Shot 2021-08-31 at 10 22 36" src="https://user-images.githubusercontent.com/43244505/131460891-c7721c21-49a5-4ae4-9864-771fdc3d3cb7.png">

Flutter example:
```dart
const Padding({
    Key? key,
    required this.padding,
    Widget? child,
  }) : assert(padding != null),
       super(key: key, child: child);
```

**Comment by passsy** [comment]
That's a great idea. Unfortunately, this repo is the wrong one to address this issue. Please move it to https://github.com/dart-lang/linter/issues

**Comment by esenmx** [comment]
Thanks for heads-up @passsy , I skipped to check repository source code :/ You can delete this issue, because there are 2 identical issues right now.

**Comment by passsy** [comment]
➡️ ref https://github.com/dart-lang/linter/issues/2913
