### ISSUE TITLE
The include file `analysis_options_package.yaml` cannot be found while developing a Flutter plugin

### ISSUE THREAD

**Issue by cdmunoz** [passsy/dart-lint#42]
While developing a Flutter plugin, after adding
```bash
dev_dependencies:
  lint: 1.6.0
```
I'm getting a warning indicating that the `analysis_options` file cannot be found.

![image](https://user-images.githubusercontent.com/1638437/133646444-7ab8ac9e-49ec-4ae7-9676-09c6bb36bb9e.png)

```bash
warning: The include file package:lint/analysis_options_package.yaml in /my/local/path/to/analysis_options.yaml cannot be found. (include_file_not_found at [my_project] analysis_options.yaml:1)
```

**Comment by passsy** [comment]
Duplicated https://github.com/passsy/dart-lint/issues/16

**Comment by passsy** [comment]
Solution https://github.com/dart-lang/sdk/issues/42910#issuecomment-851943584
