### ISSUE TITLE
avoid_redundant_argument_values ? 

### ISSUE THREAD

**Issue by AlmogRnD** [passsy/dart-lint#46]
So I'm getting avoid_redundant_argument_values but this is how Flutter widgets work in the UI for example flutter crossAxisAlignment shouldn't this be removed from the lint to set to false by default

**Comment by passsy** [comment]
Please post a code example of the problem. 

Why do you think `crossAxisAlignment: CrossAxisAlignment.center` should be provided, if it is already the default value?

**Comment by AlmogRnD** [comment]
I have this which is correct
<img width="541" alt="Screen Shot 2021-11-15 at 11 43 11 PM" src="https://user-images.githubusercontent.com/169507/141858076-ed0ab7ad-a648-4ee8-b469-d053f52b4542.png">

But getting the following warning
<img width="629" alt="Screen Shot 2021-11-15 at 11 43 24 PM" src="https://user-images.githubusercontent.com/169507/141858104-59b35c49-0b0e-49eb-8497-8d54b4b6f123.png">

**Comment by passsy** [comment]
Removing the `crossAxisAlignment` argument is also correct. You don't need to pass it because it is the [default](https://github.com/flutter/flutter/blob/245168f85c7e6ea32b2019c73b39c28f481098d0/packages/flutter/lib/src/widgets/basic.dart#L4705).

**Comment by AlmogRnD** [comment]
Ohh had no idea it was default thanks

**Comment by AlmogRnD** [comment]
Bye the way depend_on_referenced_packages happens on Generated file. might be good to ignore those files
