### ISSUE TITLE
Enable avoid_dynamic_calls

### ISSUE THREAD

**Issue by passsy** [passsy/dart-lint#47]
https://dart-lang.github.io/linter/lints/avoid_dynamic_calls.html

TODO research implications on actual code

**Comment by passsy** [comment]
enabled for now

**Comment by AlmogRnD** [comment]
Hi, this adds lots of warnings in my code and I was wondering how important is it, when I looked into it's worth noting that the mentioned size and runtime penalties are generally not a concern, they are likely to be unnoticeable. Also dynamic is used a lot for example the JSON annotation package
