### ISSUE TITLE
Broken linter around enum and import order

### ISSUE THREAD

**Issue by EA-YOUHOU** [passsy/dart-lint#55]
Hello,

I didn't find the reason, but the linter got confused around my import for no special reason (no double enum / class with the same name) and i got the following behavior which is funny : 

Enum is type DownloadType (good)
<img width="616" alt="Capture d’écran 2022-04-19 à 10 52 00" src="https://user-images.githubusercontent.com/92172436/163966735-cc53c234-559e-455e-a6f3-758ea3e3340f.png">

Enum instance variable is dynamic... 
<img width="556" alt="Capture d’écran 2022-04-19 à 10 52 05" src="https://user-images.githubusercontent.com/92172436/163966605-e1aabb5f-258b-400b-9ece-56fae31800a0.png">

When playing with import order this issue disappear but as I used this rule : directives_ordering I can't. If i remove the comma just after DownloadType downloadType, error disappear... So seems like parsing error from the linter.

**Comment by passsy** [comment]
Thanks for taking the time to report this issue. Unfortunately, this is an analyzer issue and can't be fixed by this package. You might want to report it to https://github.com/dart-lang/sdk  directly

**Comment by EA-YOUHOU** [comment]
When I comment all rules inside the analysis_optins.yaml then the error disappear and come back when enabling all rules.
Pretty sure that's it's around this package :/
