### ISSUE TITLE
Remove `implicit-casts`

### ISSUE THREAD

**Issue by jxstxn1** [passsy/dart-lint#67]
In `Flutter Beta 3.9.0-0.2.pre` our analyzer is telling us that the option `implicit-casts` is no longer supported.

The Stacktrace which I got:

```bash 
/opt/hostedtoolcache/flutter/beta-3.9.0-0.2.pre-x64/.pub-cache/hosted/pub.dev/lint-1.10.0/lib/analysis_options.yaml(281..294): The option 'implicit-casts' is no longer supported
```

**Comment by passsy** [comment]
Please update to [v2.1.0](https://github.com/passsy/dart-lint/releases/tag/v2.1.0)

**Comment by passsy** [comment]
Alternatively, ignore the warning in your `analysis_options.yaml`

```
analyzer:
  errors:
    included_file_warning: ignore
```
