### ISSUE TITLE
Add new rules for Dart 3.2

### ISSUE THREAD

**Issue by passsy** [passsy/dart-lint#70]

**Comment by Tejoooo** [comment]
@passsy can u assign me this issue i m ready to contribute

**Comment by Tejoooo** [comment]
@passsy where shld I add the documentation in which folder ?

**Comment by passsy** [comment]
I can't follow you. Which documentation?

**Comment by Tejoooo** [comment]
@passsy where do I need to add the new Dart rules in which folder ?

**Comment by passsy** [comment]
This package consists of 11 files and one folder. The Readme clearly states which ones are responsible for what.

Can you explain what you think this issue is about? I think there might be a big misunderstanding 😅

**Comment by robiness** [comment]
There seem to be [no new lints added](https://github.com/dart-lang/linter/blob/main/CHANGELOG.md) since 3.1.
So this issue might be safe to close.

**Comment by passsy** [comment]
According to the [Dart SDK Changelog](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#320) one rule has been added in 3.2:

> - Added the experimental [annotate_redeclares](https://dart.dev/lints/annotate_redeclares) lint.
> - Marked the [use_build_context_synchronously](https://dart.dev/lints/use_build_context_synchronously) lint as stable.

**Comment by robiness** [comment]
On it

**Comment by wm-jenildgohel** [comment]
do we have any update on this issue?

**Comment by passsy** [comment]
This has already been released as `lint: 2.3.0`

**Comment by wm-jenildgohel** [comment]
the version 2.3.0 does not exists! 

![image](https://github.com/passsy/dart-lint/assets/124780639/63ad9c61-7f16-4dbd-aa03-4bbb3d634e36)

**Comment by passsy** [comment]
Whoopsi, now it is :) https://pub.dev/packages/lint/versions/2.3.0
